yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AuthorStaticPage.as_view(), name='author'),
    path('tech/', views.TechStaticPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()
TEXT_POST = (
    'Автор поста {} группы {} '
    'написанный {} '
    'с текстом {:.15}')
TEXT_COMMENT = (
    'Автор коммента {} '
    'написанный {} с текстом {:.15}'
)
TEXT_FOLLOW = (
    '{} подписался на {}'
)


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        max_length=30,
        unique=True,
        verbose_name='Уникальный фрагмент'
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Сообщество'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        help_text='Добавить картинку',
        verbose_name='Картинка'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return TEXT_POST.format(
            self.author, self.group,
            self.pub_date, self.text)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Запись'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return (
            TEXT_COMMENT.format(self.author, self.created, self.text))


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def __str__(self):
        return TEXT_FOLLOW.format(str(self.user), self.author)

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow


def page(request, post_list):
    return Paginator(
        post_list,
        settings.FIRST_OF_POSTS).get_page(request.GET.get('page'))


def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': page(request, Post.objects.all())
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': page(request, group.posts.all())
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': page(request, author.posts.all()),
        'following': request.user.is_authenticated and Follow.objects.filter(
            user=request.user, author=(User.objects.get(username=username))
        ).exists(),
    })


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'form': CommentForm(),
        'comments': post.comments.select_related('author')
    })


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form
        })
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            'posts:post_detail', post_id
        )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail', post_id
        )
    return render(request, 'posts/create_post.html', {
        'form': form,
        'post': post
    })


@login_required()
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
    return redirect('posts:index')


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    return render(request, 'posts/follow.html', {
        'page_obj': page(request, (
            Post.objects.select_related(
                'author', 'group').filter(
                author__following__user=request.user)))
    })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if not (author == request.user
            or Follow.objects.filter(
                user=request.user, author=author).exists()):
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author_following = Follow.objects.filter(
        user=request.user,
        author=(get_object_or_404(User, username=username))
    )
    if author_following.exists():
        author_following.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if post %} Сохранить пост {% else %} Добавить пост {% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post %} Сохранить пост {% else %} Добавить пост {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/errors.html' %}
            <form method="post" enctype="multipart/form-data" action="
              {% if post %}
                {% url 'posts:post_edit' post.pk %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}">
              {% csrf_token %}
              {% for field in form %}
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %} Сохранить пост {% else %} Добавить пост {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html'%}
{% block title %} Избранные авторы {% endblock %}
{% block content %}
  <h1> Избранные авторы </h1>
  {% include 'posts/includes/switcher.html' with follow_index=True %}
  <article>
    {% for post in page_obj %}
      {% include 'posts/includes/post_info.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </article>
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>
      {{ group.title }}
    </h1>
    <p>
      {{ group.description|linebreaksbr }}
    </p>
    {% for post in page_obj %}
      <article>
        {% include 'posts/includes/post_info.html' %}
        {% if not forloop.last %} <hr> {% endif %}
      </article>
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with index=True %}
  {% load cache %}
  {% cache 20 sidebar index page_obj.number %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_info.html' %}
      {% if post.group %}
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} Пост {{ post.text}} {% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="container col-lg-9 col-sm-12">
    <div class="row">
      <aside class="col-12 col-md-4">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
                Дата публикации:
            <br>
            {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
                Сообщество:
              <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
            </li>
          {% endif %}
          <li class="list-group-item">
              Автор:
            <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
          </li>
          <li class="list-group-item">
              Всего постов автора:
            {{ post.author.posts.count }}
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-8">
        <p>
          {% thumbnail post.image "960x500" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {{ post.text|linebreaks }}
        </p>
        {% if post.author == user %}
          <form action="{% url 'posts:post_edit' post.pk %}">
            <button type="submit" class="btn btn-primary">Редактировать</button>
          </form>
          <form action="{% url 'posts:post_delete' post.pk %}">
            <button type="submit" class="btn btn-primary">Удалить</button>
          </form>
        {% endif %}
    </div>
    {% include 'posts/includes/comments.html' %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профиль пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}

  <div class="mb-5">
    <h2>Все посты пользователя {{ author.get_full_name }} </h2>
    <h6>Всего постов: {{ author.posts.count }}</h6>
    <h6>Подписок: {{ author.follower.count }} </h6>
    <h6>Подписчиков: {{ author.following.count }} </h6>
    <h6>Комментариев: {{ author.comments.count }} </h6>
    {% if user.is_authenticated and user !=  author %}
      {% if following %}
        <a class="btn btn-lg btn-light"
           href="{% url 'posts:profile_unfollow' author.username %}"
           role="button">
          Отписаться
        </a>
      {% else %}
        <a class="btn btn-lg btn-primary"
           href="{% url 'posts:profile_follow' author.username %}"
           role="button">
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    <hr>
    {% for post in page_obj %}
      <article>
        {% include 'posts/includes/post_info.html' %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}